name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:humble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2 environment
        run: |
          apt update && apt install -y python3-colcon-common-extensions
          source /opt/ros/humble/setup.bash

      - name: Build workspace
        run: |
          mkdir -p ~/ros2_ws/src
          cp -r . ~/ros2_ws/src/
          cd ~/ros2_ws
          colcon build --symlink-install

      - name: Run tests
        run: |
          cd ~/ros2_ws
          colcon test --event-handlers console_cohesion+
          colcon test-result --verbose
