name: ROS 2 Humble Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up ROS 2 Humble
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2.list'
        sudo apt update
        sudo apt install -y ros-humble-desktop
        sudo apt install -y python3-colcon-common-extensions

    - name: Source ROS 2 setup script
      run: |
        source /opt/ros/humble/setup.sh
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y
      shell: bash
      env:
        LANG: en_US.UTF-8
