name: ROS 2 Humble Workflow

on:
  push:
    branches:
      - humble

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Clona el repositorio en $GITHUB_WORKSPACE

    - name: Set up ROS 2 Humble
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2.list'
        sudo apt update
        sudo apt install -y ros-humble-desktop
        sudo apt install -y python3-colcon-common-extensions
        sudo apt install -y python3-rosdep2  # Instala rosdep

    - name: Initialize rosdep (if not already initialized)
      run: |
        if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then
          sudo rosdep init
        fi
        rosdep update

    - name: Set up workspace and copy repo to src
      run: |
        mkdir -p ~/ros2_ws/src  # Crea el workspace y el directorio src
        
        echo "Verificando contenido de $GITHUB_WORKSPACE antes de copiar"
        ls -la $GITHUB_WORKSPACE  # Depuración

        cp -r $GITHUB_WORKSPACE/* ~/ros2_ws/src/  # Copia el contenido del repo a src
        
        echo "Verificando contenido de ~/ros2_ws/src/ después de copiar"
        ls -la ~/ros2_ws/src/  # Depuración

    - name: Verify src directory before installing dependencies
      run: |
        if [ ! -d "$HOME/ros2_ws/src" ] || [ -z "$(ls -A $HOME/ros2_ws/src)" ]; then
          echo "Error: El directorio src está vacío o no existe."
          exit 1
        fi

    - name: Install dependencies with rosdep
      run: |
        source /opt/ros/humble/setup.sh
        cd ~/ros2_ws
        rosdep install --from-paths src --ignore-src -r -y  # Instala dependencias

    - name: Build workspace
      run: |
        cd ~/ros2_ws
        colcon build --symlink-install  # Compila el workspace

    - name: Run tests
      run: |
        cd ~/ros2_ws
        colcon test --event-handlers console_cohesion+  # Ejecuta las pruebas
        colcon test-result --verbose  # Muestra los resultados de las pruebas
