name: Build and Test

on:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:humble

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup ROS 2 environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble

      - name: Install ROS 2 build tools
        run: |
          sudo apt update
          sudo apt install -y ros-humble-ament-cmake

      - name: Install dependencies using rosdep
        run: |
          source /opt/ros/humble/setup.bash
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build workspace
        run: |
          mkdir -p ~/ros2_ws/src
          cp -r . ~/ros2_ws/src/
          cd ~/ros2_ws
          colcon build --symlink-install

      - name: Run tests
        run: |
          cd ~/ros2_ws
          colcon test --event-handlers console_cohesion+
          colcon test-result --verbose
