name: ROS 2 Humble Workflow

on:
  push:
    branches:
      - humble

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Fix broken packages
      run: |
        sudo apt update
        sudo apt --fix-broken install -y
        sudo apt clean
        sudo apt autoremove -y

    - name: Enable universe repository and update
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install -y libunwind-dev

    - name: Install ROS 2 Humble (without navigation2)
      run: |
        sudo apt install -y \
          ros-humble-desktop \
          python3-colcon-common-extensions \
          python3-rosdep2

    - name: Install navigation2 manually
      run: |
        sudo apt install -y \
          ros-humble-navigation2 \
          ros-humble-nav2-bringup \
          ros-humble-nav2-core \
          ros-humble-nav2-util \
          ros-humble-nav2-msgs \
          ros-humble-nav2-common \
          ros-humble-nav2-behaviors || true  # Ignorar errores y continuar

    - name: Set up workspace and copy repo to src
      run: |
        mkdir -p ~/ros2_ws/src
        cp -r $GITHUB_WORKSPACE/* ~/ros2_ws/src/
        ls -la ~/ros2_ws/src/

    - name: Install dependencies with rosdep
      run: |
        source /opt/ros/humble/setup.sh
        cd ~/ros2_ws
        rosdep install --from-paths src --ignore-src -r -y || true

    - name: Build workspace
      run: |
        cd ~/ros2_ws
        colcon build --symlink-install --cmake-clean-cache

    - name: Run tests
      run: |
        cd ~/ros2_ws
        colcon test --event-handlers console_cohesion+
        colcon test-result --verbose
