name: ROS 2 Humble Workflow

on:
  push:
    branches:
      - humble

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up ROS 2 Humble
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2.list'
        sudo apt update
        sudo apt install -y ros-humble-desktop python3-colcon-common-extensions python3-rosdep2

    - name: Install missing dependencies
      run: |
        sudo apt update
        sudo apt install -y ros-humble-ament-cmake ros-humble-ament-lint ros-humble-ament-cmake-auto

    - name: Initialize rosdep
      run: |
        if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then
          sudo rosdep init
        fi
        rosdep update

    - name: Set up workspace and copy repo to src
      run: |
        mkdir -p ~/ros2_ws/src
        cp -r $GITHUB_WORKSPACE/* ~/ros2_ws/src/
        ls -la ~/ros2_ws/src/

    - name: Source ROS 2 environment
      run: |
        source /opt/ros/humble/setup.sh
        echo "CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH"
        env | grep ROS

    - name: Install dependencies with rosdep
      run: |
        source /opt/ros/humble/setup.sh
        cd ~/ros2_ws
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build workspace
      run: |
        cd ~/ros2_ws
        colcon build --symlink-install --cmake-clean-cache

    - name: Run tests
      run: |
        cd ~/ros2_ws
        colcon test --event-handlers console_cohesion+
        colcon test-result --verbose
