name: ROS 2 Humble Workflow

on:
  push:
    branches:
      - humble

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Add ROS 2 repository
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2.list'
        sudo apt update

    - name: Enable universe repository
      run: |
        sudo add-apt-repository universe
        sudo apt update

    - name: Install ROS 2 Humble
      run: |
        sudo apt install -y ros-humble-desktop python3-colcon-common-extensions python3-rosdep2

    - name: Install ament_cmake and dependencies
      run: |
        sudo apt update
        sudo apt install -y ros-humble-ament-cmake
        sudo apt install -y python3-colcon-common-extensions

    - name: Install Nav2 and related packages
      run: |
        sudo apt install -y \
          ros-humble-navigation2 \
          ros-humble-nav2-bringup \
          ros-humble-nav2-core \
          ros-humble-nav2-util \
          ros-humble-nav2-msgs \
          ros-humble-nav2-common \
          ros-humble-nav2-behaviors

    - name: Initialize rosdep
      run: |
        sudo rosdep init || true
        rosdep update

    - name: Set up workspace
      run: |
        mkdir -p ~/ros2_ws/src
        cp -r $GITHUB_WORKSPACE/* ~/ros2_ws/src/

    - name: Install dependencies with rosdep
      run: |
        source /opt/ros/humble/setup.sh
        cd ~/ros2_ws
        rosdep install --from-paths src --ignore-src -r -y || true

    - name: Build workspace
      run: |
        cd ~/ros2_ws
        colcon build --symlink-install --cmake-clean-cache

    - name: Run tests
      run: |
        cd ~/ros2_ws
        colcon test --event-handlers console_cohesion+
        colcon test-result --verbose
