name: Build and Test

on:
  push:
    branches:
      - humble
  pull_request:
    branches:
      - humble

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:humble

    steps:
      # Checkout del código fuente
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar el entorno de ROS 2 usando setup-ros
      - name: Setup ROS 2 environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
          # Si deseas agregar más distribuciones o configuraciones adicionales, puedes hacerlo aquí

      # Construir el workspace
      - name: Build workspace
        run: |
          mkdir -p ~/ros2_ws/src
          cp -r . ~/ros2_ws/src/
          cd ~/ros2_ws
          colcon build --symlink-install

      # Ejecutar los tests
      - name: Run tests
        run: |
          cd ~/ros2_ws
          colcon test --event-handlers console_cohesion+
          colcon test-result --verbose
